name: Artifacts
on:
  workflow_dispatch:

jobs:
  artifact-producer:
    name: Produce artifact
    runs-on: ubuntu-24.04
    steps:
      - name: Create artifact file
        run: |
          echo "##################################" >> example.txt
          echo "# This is the header of the file #" >> example.txt
          echo "##################################" >> example.txt
          echo "Hello World!!!" >> example.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-artifact # set artifact name
          path: example.txt
          retention-days: 1
  artifact-consumer:
    name: Consume artifact
    runs-on: ubuntu-24.04
    needs: artifact-producer
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: example-artifact # artifact name
      - name: Read artifact
        run: cat example.txt



